// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSync():Promise<void>;

export function ChooseSyncDir():Promise<string>;

export function GetAnnouncements(arg1:number):Promise<Array<main.Announcement>>;

export function GetCourses():Promise<Array<main.Course>>;

export function GetDeadlines():Promise<Array<main.Deadline>>;

export function GetGrades():Promise<Array<main.Grade>>;

export function GetRecentFiles(arg1:number):Promise<Array<main.FileNode>>;

export function GetSettings():Promise<main.Settings>;

export function GetStats():Promise<main.Stats>;

export function GetSyncStatus():Promise<main.SyncStatus>;

export function GetTelegramStatus():Promise<main.TelegramStatus>;

export function GetTree(arg1:number):Promise<Array<main.FileNode>>;

export function Init(arg1:boolean):Promise<void>;

export function MarkAnnouncementRead(arg1:number):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PairTelegram():Promise<string>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<main.SearchHit>>;

export function SendTestTelegram():Promise<void>;

export function SetCourseEnabled(arg1:number,arg2:boolean):Promise<void>;

export function SyncNow():Promise<void>;

export function TestCanvas():Promise<string>;
