// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaperToLibrary(arg1) {
  return window['go']['main']['App']['AddPaperToLibrary'](arg1);
}

export function CancelStudyJob(arg1) {
  return window['go']['main']['App']['CancelStudyJob'](arg1);
}

export function CancelSync() {
  return window['go']['main']['App']['CancelSync']();
}

export function ChooseSyncDir() {
  return window['go']['main']['App']['ChooseSyncDir']();
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DownloadPaperPDF(arg1) {
  return window['go']['main']['App']['DownloadPaperPDF'](arg1);
}

export function ExportBibTeX(arg1) {
  return window['go']['main']['App']['ExportBibTeX'](arg1);
}

export function GetAnnouncements(arg1) {
  return window['go']['main']['App']['GetAnnouncements'](arg1);
}

export function GetAsks(arg1) {
  return window['go']['main']['App']['GetAsks'](arg1);
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChats(arg1, arg2) {
  return window['go']['main']['App']['GetChats'](arg1, arg2);
}

export function GetCitations(arg1, arg2) {
  return window['go']['main']['App']['GetCitations'](arg1, arg2);
}

export function GetCourses() {
  return window['go']['main']['App']['GetCourses']();
}

export function GetDeadlineDetail(arg1) {
  return window['go']['main']['App']['GetDeadlineDetail'](arg1);
}

export function GetDeadlines() {
  return window['go']['main']['App']['GetDeadlines']();
}

export function GetDueFlashcards(arg1) {
  return window['go']['main']['App']['GetDueFlashcards'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFilePageCount(arg1) {
  return window['go']['main']['App']['GetFilePageCount'](arg1);
}

export function GetFileText(arg1, arg2) {
  return window['go']['main']['App']['GetFileText'](arg1, arg2);
}

export function GetGrades() {
  return window['go']['main']['App']['GetGrades']();
}

export function GetLibrary(arg1) {
  return window['go']['main']['App']['GetLibrary'](arg1);
}

export function GetOverview(arg1) {
  return window['go']['main']['App']['GetOverview'](arg1);
}

export function GetPaper(arg1) {
  return window['go']['main']['App']['GetPaper'](arg1);
}

export function GetPaperDigest(arg1) {
  return window['go']['main']['App']['GetPaperDigest'](arg1);
}

export function GetPaperSummary(arg1) {
  return window['go']['main']['App']['GetPaperSummary'](arg1);
}

export function GetPaperTelegramStatus() {
  return window['go']['main']['App']['GetPaperTelegramStatus']();
}

export function GetQuiz(arg1) {
  return window['go']['main']['App']['GetQuiz'](arg1);
}

export function GetQuizAttempts(arg1) {
  return window['go']['main']['App']['GetQuizAttempts'](arg1);
}

export function GetQuizzes(arg1) {
  return window['go']['main']['App']['GetQuizzes'](arg1);
}

export function GetRecentFiles(arg1) {
  return window['go']['main']['App']['GetRecentFiles'](arg1);
}

export function GetRecommendations(arg1) {
  return window['go']['main']['App']['GetRecommendations'](arg1);
}

export function GetReferences(arg1, arg2) {
  return window['go']['main']['App']['GetReferences'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStudyJob(arg1) {
  return window['go']['main']['App']['GetStudyJob'](arg1);
}

export function GetStudyJobs() {
  return window['go']['main']['App']['GetStudyJobs']();
}

export function GetStudyStatus() {
  return window['go']['main']['App']['GetStudyStatus']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTelegramStatus() {
  return window['go']['main']['App']['GetTelegramStatus']();
}

export function GetTree(arg1) {
  return window['go']['main']['App']['GetTree'](arg1);
}

export function GetUnseenCount() {
  return window['go']['main']['App']['GetUnseenCount']();
}

export function GetWhatsNew(arg1) {
  return window['go']['main']['App']['GetWhatsNew'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Init(arg1) {
  return window['go']['main']['App']['Init'](arg1);
}

export function MarkAnnouncementRead(arg1) {
  return window['go']['main']['App']['MarkAnnouncementRead'](arg1);
}

export function MarkFeedSeen() {
  return window['go']['main']['App']['MarkFeedSeen']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenScholar(arg1) {
  return window['go']['main']['App']['OpenScholar'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PairPaperTelegram() {
  return window['go']['main']['App']['PairPaperTelegram']();
}

export function PairTelegram() {
  return window['go']['main']['App']['PairTelegram']();
}

export function RemovePaperFromLibrary(arg1) {
  return window['go']['main']['App']['RemovePaperFromLibrary'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function ReviewFlashcard(arg1, arg2) {
  return window['go']['main']['App']['ReviewFlashcard'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SearchPapers(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchPapers'](arg1, arg2, arg3);
}

export function SendChat(arg1, arg2) {
  return window['go']['main']['App']['SendChat'](arg1, arg2);
}

export function SendPaperDigestNow() {
  return window['go']['main']['App']['SendPaperDigestNow']();
}

export function SendPaperTestTelegram() {
  return window['go']['main']['App']['SendPaperTestTelegram']();
}

export function SendTestTelegram() {
  return window['go']['main']['App']['SendTestTelegram']();
}

export function SetCourseEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetCourseEnabled'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAsk(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAsk'](arg1, arg2, arg3);
}

export function StartChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartChat'](arg1, arg2, arg3);
}

export function StartFlashcards(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartFlashcards'](arg1, arg2, arg3);
}

export function StartOverview(arg1, arg2) {
  return window['go']['main']['App']['StartOverview'](arg1, arg2);
}

export function StartPaperSummary(arg1, arg2) {
  return window['go']['main']['App']['StartPaperSummary'](arg1, arg2);
}

export function StartQuiz(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartQuiz'](arg1, arg2, arg3);
}

export function SubmitQuizAttempt(arg1) {
  return window['go']['main']['App']['SubmitQuizAttempt'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TestCanvas() {
  return window['go']['main']['App']['TestCanvas']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateLibraryPaper(arg1) {
  return window['go']['main']['App']['UpdateLibraryPaper'](arg1);
}
