// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelStudyJob(arg1:string):Promise<void>;

export function CancelSync():Promise<void>;

export function ChooseSyncDir():Promise<string>;

export function GetAnnouncements(arg1:number):Promise<Array<main.Announcement>>;

export function GetAsks(arg1:number):Promise<Array<main.AskResult>>;

export function GetCourses():Promise<Array<main.Course>>;

export function GetDeadlineDetail(arg1:number):Promise<main.Deadline>;

export function GetDeadlines():Promise<Array<main.Deadline>>;

export function GetDueFlashcards(arg1:number):Promise<Array<main.Flashcard>>;

export function GetFilePageCount(arg1:number):Promise<number>;

export function GetGrades():Promise<Array<main.Grade>>;

export function GetOverview(arg1:number):Promise<main.Overview>;

export function GetQuiz(arg1:number):Promise<main.Quiz>;

export function GetQuizAttempts(arg1:number):Promise<Array<main.QuizAttempt>>;

export function GetQuizzes(arg1:number):Promise<Array<main.Quiz>>;

export function GetRecentFiles(arg1:number):Promise<Array<main.FileNode>>;

export function GetSettings():Promise<main.Settings>;

export function GetStats():Promise<main.Stats>;

export function GetStudyJob(arg1:string):Promise<main.StudyJob>;

export function GetStudyJobs():Promise<Array<main.StudyJob>>;

export function GetStudyStatus():Promise<main.StudyStatus>;

export function GetSyncStatus():Promise<main.SyncStatus>;

export function GetTelegramStatus():Promise<main.TelegramStatus>;

export function GetTree(arg1:number):Promise<Array<main.FileNode>>;

export function GetUnseenCount():Promise<number>;

export function GetWhatsNew(arg1:number):Promise<Array<main.FeedItem>>;

export function HideWindow():Promise<void>;

export function Init(arg1:boolean):Promise<void>;

export function MarkAnnouncementRead(arg1:number):Promise<void>;

export function MarkFeedSeen():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PairTelegram():Promise<string>;

export function RevealFile(arg1:string):Promise<void>;

export function ReviewFlashcard(arg1:number,arg2:number):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<main.SearchHit>>;

export function SendTestTelegram():Promise<void>;

export function SetCourseEnabled(arg1:number,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAsk(arg1:Array<number>,arg2:string,arg3:string):Promise<string>;

export function StartFlashcards(arg1:number,arg2:string,arg3:number):Promise<string>;

export function StartOverview(arg1:number,arg2:string):Promise<string>;

export function StartQuiz(arg1:Array<number>,arg2:string,arg3:number):Promise<string>;

export function SubmitQuizAttempt(arg1:main.QuizAttempt):Promise<main.QuizAttempt>;

export function SyncNow():Promise<void>;

export function TestCanvas():Promise<string>;

export function ToggleWindow():Promise<void>;
