// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSync() {
  return window['go']['main']['App']['CancelSync']();
}

export function ChooseSyncDir() {
  return window['go']['main']['App']['ChooseSyncDir']();
}

export function GetAnnouncements(arg1) {
  return window['go']['main']['App']['GetAnnouncements'](arg1);
}

export function GetCourses() {
  return window['go']['main']['App']['GetCourses']();
}

export function GetDeadlines() {
  return window['go']['main']['App']['GetDeadlines']();
}

export function GetGrades() {
  return window['go']['main']['App']['GetGrades']();
}

export function GetRecentFiles(arg1) {
  return window['go']['main']['App']['GetRecentFiles'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTelegramStatus() {
  return window['go']['main']['App']['GetTelegramStatus']();
}

export function GetTree(arg1) {
  return window['go']['main']['App']['GetTree'](arg1);
}

export function Init(arg1) {
  return window['go']['main']['App']['Init'](arg1);
}

export function MarkAnnouncementRead(arg1) {
  return window['go']['main']['App']['MarkAnnouncementRead'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PairTelegram() {
  return window['go']['main']['App']['PairTelegram']();
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SendTestTelegram() {
  return window['go']['main']['App']['SendTestTelegram']();
}

export function SetCourseEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetCourseEnabled'](arg1, arg2);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function TestCanvas() {
  return window['go']['main']['App']['TestCanvas']();
}
