/**
 * Single entry point for everything the UI needs from the backend.
 *
 * Inside the Wails shell `window.go.main.App` exists and every call is
 * forwarded to Go. In a plain browser (`npm run dev`) the mock backend in
 * ./mock.ts is used instead, so the whole UI is developable standalone.
 *
 * Nothing in the app imports from `frontend/wailsjs/` directly — that folder
 * is regenerated by Wails on build and only carries a Greet stub today.
 */

import { localEmitter, mockAPI } from './mock';
import type {
  Announcement,
  AppAPI,
  AppEvent,
  AskResult,
  ChatMessage,
  ChatSession,
  CitationLink,
  Course,
  Deadline,
  FeedItem,
  FileNode,
  Flashcard,
  Grade,
  Overview,
  Paper,
  PaperDigest,
  PaperSearchResult,
  PaperSummary,
  LibraryPaper,
  Quiz,
  QuizAttempt,
  SearchHit,
  Settings,
  Stats,
  StudyJob,
  StudyStatus,
  SyncStatus,
  TelegramStatus,
} from './types';

export * from './types';

declare global {
  interface Window {
    go?: any;
    runtime?: any;
  }
}

/** True when running inside the Wails desktop shell. */
export function isWails(): boolean {
  return typeof window !== 'undefined' && !!window.go?.main?.App;
}

/** True when the Wails runtime (events, window controls) is present. */
function hasRuntime(): boolean {
  return typeof window !== 'undefined' && typeof window.runtime?.EventsOn === 'function';
}

/** Invoke a bound Go method, falling back to the mock implementation. */
function call<K extends keyof AppAPI>(method: K, ...args: Parameters<AppAPI[K]>): ReturnType<AppAPI[K]> {
  if (isWails()) {
    const fn = window.go.main.App[method as string];
    if (typeof fn === 'function') {
      return Promise.resolve(fn(...args)) as ReturnType<AppAPI[K]>;
    }
    console.warn(`[api] window.go.main.App.${String(method)} is missing; using mock`);
  }
  return (mockAPI[method] as any)(...args);
}

export const api = {
  getCourses: (): Promise<Course[]> => call('GetCourses'),
  setCourseEnabled: (id: number, enabled: boolean): Promise<void> => call('SetCourseEnabled', id, enabled),
  getTree: (courseID: number): Promise<FileNode[]> => call('GetTree', courseID),
  getRecentFiles: (limit: number): Promise<FileNode[]> => call('GetRecentFiles', limit),
  search: (query: string, courseID: number): Promise<SearchHit[]> => call('Search', query, courseID),
  getFileInfo: (fileID: number): Promise<FileNode> => call('GetFileInfo', fileID),
  getFileText: (fileID: number, maxChars: number): Promise<string> => call('GetFileText', fileID, maxChars),
  openFile: (path: string): Promise<void> => call('OpenFile', path),
  revealFile: (path: string): Promise<void> => call('RevealFile', path),
  openURL: (url: string): Promise<void> => call('OpenURL', url),
  syncNow: (): Promise<void> => call('SyncNow'),
  cancelSync: (): Promise<void> => call('CancelSync'),
  getSyncStatus: (): Promise<SyncStatus> => call('GetSyncStatus'),
  getDeadlines: (): Promise<Deadline[]> => call('GetDeadlines'),
  getAnnouncements: (limit: number): Promise<Announcement[]> => call('GetAnnouncements', limit),
  markAnnouncementRead: (id: number): Promise<void> => call('MarkAnnouncementRead', id),
  markAllAnnouncementsRead: (): Promise<void> => call('MarkAllAnnouncementsRead'),
  getGrades: (): Promise<Grade[]> => call('GetGrades'),
  getSettings: (): Promise<Settings> => call('GetSettings'),
  saveSettings: (s: Settings): Promise<void> => call('SaveSettings', s),
  testCanvas: (): Promise<string> => call('TestCanvas'),
  getTelegramStatus: (): Promise<TelegramStatus> => call('GetTelegramStatus'),
  pairTelegram: (): Promise<string> => call('PairTelegram'),
  sendTestTelegram: (): Promise<void> => call('SendTestTelegram'),
  chooseSyncDir: (): Promise<string> => call('ChooseSyncDir'),
  getStats: (): Promise<Stats> => call('GetStats'),

  // ------------------------------------------------------------ what's new
  getWhatsNew: (sinceDays: number): Promise<FeedItem[]> => call('GetWhatsNew', sinceDays),
  markFeedSeen: (): Promise<void> => call('MarkFeedSeen'),
  getUnseenCount: (): Promise<number> => call('GetUnseenCount'),

  // ------------------------------------------------------- deadline detail
  getDeadlineDetail: (id: number): Promise<Deadline> => call('GetDeadlineDetail', id),

  // ------------------------------------------------------- window control
  showWindow: (): Promise<void> => call('ShowWindow'),
  hideWindow: (): Promise<void> => call('HideWindow'),
  toggleWindow: (): Promise<void> => call('ToggleWindow'),

  // ----------------------------------------------------------------- study
  getStudyStatus: (): Promise<StudyStatus> => call('GetStudyStatus'),
  startOverview: (fileID: number, model: string): Promise<string> => call('StartOverview', fileID, model),
  getOverview: (fileID: number): Promise<Overview> => call('GetOverview', fileID),
  startQuiz: (fileIDs: number[], model: string, n: number): Promise<string> => call('StartQuiz', fileIDs, model, n),
  getQuizzes: (fileID: number): Promise<Quiz[]> => call('GetQuizzes', fileID),
  getQuiz: (id: number): Promise<Quiz> => call('GetQuiz', id),
  submitQuizAttempt: (a: QuizAttempt): Promise<QuizAttempt> => call('SubmitQuizAttempt', a),
  getQuizAttempts: (quizID: number): Promise<QuizAttempt[]> => call('GetQuizAttempts', quizID),
  startAsk: (fileIDs: number[], question: string, model: string): Promise<string> =>
    call('StartAsk', fileIDs, question, model),
  getAsks: (fileID: number): Promise<AskResult[]> => call('GetAsks', fileID),
  startFlashcards: (fileID: number, model: string, n: number): Promise<string> =>
    call('StartFlashcards', fileID, model, n),
  getDueFlashcards: (limit: number): Promise<Flashcard[]> => call('GetDueFlashcards', limit),
  reviewFlashcard: (id: number, grade: number): Promise<void> => call('ReviewFlashcard', id, grade),
  getStudyJob: (id: string): Promise<StudyJob> => call('GetStudyJob', id),
  getStudyJobs: (): Promise<StudyJob[]> => call('GetStudyJobs'),
  cancelStudyJob: (id: string): Promise<void> => call('CancelStudyJob', id),
  getFilePageCount: (fileID: number): Promise<number> => call('GetFilePageCount', fileID),

  // ---------------------------------------------------------------- papers
  searchPapers: (query: string, source: string, limit: number): Promise<PaperSearchResult> =>
    call('SearchPapers', query, source, limit),
  getPaper: (id: string): Promise<Paper> => call('GetPaper', id),
  addPaperToLibrary: (p: Paper): Promise<LibraryPaper> => call('AddPaperToLibrary', p),
  removePaperFromLibrary: (id: string): Promise<void> => call('RemovePaperFromLibrary', id),
  getLibrary: (status: string): Promise<LibraryPaper[]> => call('GetLibrary', status),
  updateLibraryPaper: (lp: LibraryPaper): Promise<LibraryPaper> => call('UpdateLibraryPaper', lp),
  downloadPaperPDF: (id: string): Promise<LibraryPaper> => call('DownloadPaperPDF', id),
  getCitations: (id: string, limit: number): Promise<CitationLink[]> => call('GetCitations', id, limit),
  getReferences: (id: string, limit: number): Promise<CitationLink[]> => call('GetReferences', id, limit),
  getRecommendations: (limit: number): Promise<Paper[]> => call('GetRecommendations', limit),
  getPaperDigest: (date: string): Promise<PaperDigest> => call('GetPaperDigest', date),
  sendPaperDigestNow: (): Promise<void> => call('SendPaperDigestNow'),
  exportBibTeX: (ids: string[]): Promise<string> => call('ExportBibTeX', ids),
  openScholar: (query: string): Promise<void> => call('OpenScholar', query),
  startPaperSummary: (paperID: string, model: string): Promise<string> =>
    call('StartPaperSummary', paperID, model),
  getPaperSummary: (paperID: string): Promise<PaperSummary> => call('GetPaperSummary', paperID),
  pairPaperTelegram: (): Promise<string> => call('PairPaperTelegram'),
  getPaperTelegramStatus: (): Promise<TelegramStatus> => call('GetPaperTelegramStatus'),
  sendPaperTestTelegram: (): Promise<void> => call('SendPaperTestTelegram'),

  // ------------------------------------------------------------------ chat
  startChat: (fileID: number, paperID: string, model: string): Promise<ChatSession> =>
    call('StartChat', fileID, paperID, model),
  sendChat: (sessionID: string, message: string): Promise<string> => call('SendChat', sessionID, message),
  getChats: (fileID: number, paperID: string): Promise<ChatSession[]> => call('GetChats', fileID, paperID),
  getChatMessages: (sessionID: string): Promise<ChatMessage[]> => call('GetChatMessages', sessionID),
  deleteChat: (sessionID: string): Promise<void> => call('DeleteChat', sessionID),
};

/**
 * Subscribe to a backend event. Uses the Wails runtime when available,
 * otherwise the mock's local emitter. Returns an unsubscribe function.
 */
export function on(event: AppEvent, cb: (...args: any[]) => void): () => void {
  if (hasRuntime()) {
    const off = window.runtime.EventsOn(event, cb);
    return typeof off === 'function'
      ? off
      : () => window.runtime.EventsOff?.(event);
  }
  return localEmitter.on(event, cb);
}

/** Emit an event locally (used by the UI to raise its own toasts). */
export function emitLocal(event: AppEvent, ...args: any[]): void {
  localEmitter.emit(event, ...args);
}

/** Normalise unknown errors coming back from Go into a message string. */
export function errMsg(err: unknown): string {
  if (!err) return 'Unknown error';
  if (typeof err === 'string') return err;
  if (err instanceof Error) return err.message;
  const anyErr = err as any;
  return anyErr?.message ?? String(err);
}
