/**
 * Single entry point for everything the UI needs from the backend.
 *
 * Inside the Wails shell `window.go.main.App` exists and every call is
 * forwarded to Go. In a plain browser (`npm run dev`) the mock backend in
 * ./mock.ts is used instead, so the whole UI is developable standalone.
 *
 * Nothing in the app imports from `frontend/wailsjs/` directly — that folder
 * is regenerated by Wails on build and only carries a Greet stub today.
 */

import { localEmitter, mockAPI } from './mock';
import type {
  Announcement,
  AppAPI,
  AppEvent,
  Course,
  Deadline,
  FileNode,
  Grade,
  SearchHit,
  Settings,
  Stats,
  SyncStatus,
  TelegramStatus,
} from './types';

export * from './types';

declare global {
  interface Window {
    go?: any;
    runtime?: any;
  }
}

/** True when running inside the Wails desktop shell. */
export function isWails(): boolean {
  return typeof window !== 'undefined' && !!window.go?.main?.App;
}

/** True when the Wails runtime (events, window controls) is present. */
function hasRuntime(): boolean {
  return typeof window !== 'undefined' && typeof window.runtime?.EventsOn === 'function';
}

/** Invoke a bound Go method, falling back to the mock implementation. */
function call<K extends keyof AppAPI>(method: K, ...args: Parameters<AppAPI[K]>): ReturnType<AppAPI[K]> {
  if (isWails()) {
    const fn = window.go.main.App[method as string];
    if (typeof fn === 'function') {
      return Promise.resolve(fn(...args)) as ReturnType<AppAPI[K]>;
    }
    console.warn(`[api] window.go.main.App.${String(method)} is missing; using mock`);
  }
  return (mockAPI[method] as any)(...args);
}

export const api = {
  getCourses: (): Promise<Course[]> => call('GetCourses'),
  setCourseEnabled: (id: number, enabled: boolean): Promise<void> => call('SetCourseEnabled', id, enabled),
  getTree: (courseID: number): Promise<FileNode[]> => call('GetTree', courseID),
  getRecentFiles: (limit: number): Promise<FileNode[]> => call('GetRecentFiles', limit),
  search: (query: string, courseID: number): Promise<SearchHit[]> => call('Search', query, courseID),
  openFile: (path: string): Promise<void> => call('OpenFile', path),
  revealFile: (path: string): Promise<void> => call('RevealFile', path),
  openURL: (url: string): Promise<void> => call('OpenURL', url),
  syncNow: (): Promise<void> => call('SyncNow'),
  cancelSync: (): Promise<void> => call('CancelSync'),
  getSyncStatus: (): Promise<SyncStatus> => call('GetSyncStatus'),
  getDeadlines: (): Promise<Deadline[]> => call('GetDeadlines'),
  getAnnouncements: (limit: number): Promise<Announcement[]> => call('GetAnnouncements', limit),
  markAnnouncementRead: (id: number): Promise<void> => call('MarkAnnouncementRead', id),
  getGrades: (): Promise<Grade[]> => call('GetGrades'),
  getSettings: (): Promise<Settings> => call('GetSettings'),
  saveSettings: (s: Settings): Promise<void> => call('SaveSettings', s),
  testCanvas: (): Promise<string> => call('TestCanvas'),
  getTelegramStatus: (): Promise<TelegramStatus> => call('GetTelegramStatus'),
  pairTelegram: (): Promise<string> => call('PairTelegram'),
  sendTestTelegram: (): Promise<void> => call('SendTestTelegram'),
  chooseSyncDir: (): Promise<string> => call('ChooseSyncDir'),
  getStats: (): Promise<Stats> => call('GetStats'),
};

/**
 * Subscribe to a backend event. Uses the Wails runtime when available,
 * otherwise the mock's local emitter. Returns an unsubscribe function.
 */
export function on(event: AppEvent, cb: (...args: any[]) => void): () => void {
  if (hasRuntime()) {
    const off = window.runtime.EventsOn(event, cb);
    return typeof off === 'function'
      ? off
      : () => window.runtime.EventsOff?.(event);
  }
  return localEmitter.on(event, cb);
}

/** Emit an event locally (used by the UI to raise its own toasts). */
export function emitLocal(event: AppEvent, ...args: any[]): void {
  localEmitter.emit(event, ...args);
}

/** Normalise unknown errors coming back from Go into a message string. */
export function errMsg(err: unknown): string {
  if (!err) return 'Unknown error';
  if (typeof err === 'string') return err;
  if (err instanceof Error) return err.message;
  const anyErr = err as any;
  return anyErr?.message ?? String(err);
}
